# This workflows will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7, 3.8, 3.9, 3.10.0 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev
    - name: Test with unittest
      run: |
        pipenv run coverage run --source='.' tests.py -v
        pipenv run coverage xml -o coverage.xml
    - name: Check with isort
      run: |
        pipenv run isort . --profile black
    - name: Check with mypy
      run: |
        pipenv run mypy .
    - name: Check if coverage under 95
      run: |
        pipenv run coverage report --fail-under=95